### ISSUE TITLE
Nice work Elias

### ISSUE THREAD

**Issue by meyadd** [Elias011/elias.js#7]
I have some notes :
1- you used a tag "h0" to display the title of the page,it is not a standard html element, so you can use "p,div,.." instead of it

2- it is not necessary to set the id of the elements if you do not use it, and the id usually is a unique string value with alphabetic and numeric characters, so it is not standard to set :
`<img id="image/aleph.jpg">`
`<h2 id="Author: Paulo-Coelho <br>">`
`<h3 id="Language: Portuguese">`
(the first book in the page)

3- you included the images of the books in the books object ("info"),that is good in the practical situation, but our task was to create a new object "images_object" that contains the images of the book,then you should search in the DOM to find every book by id and append a image to it, the image takes its source "src" from "images_object"

**Comment by Elias011** [comment]
Hi Eyad thank you man for your notes 
about the first note you are right I fixed to p1
about the second note you are also right, actually I made them for a little bit help me by CSS but I didn't use them and I just forgot them, now I removed them.
about the third note, I don't see a large difference between what I made and what our task said, but yes we should do what the task says so I fixed it as what as what we should to do
