### ISSUE TITLE
it is better to have a shorter id

### ISSUE THREAD

**Issue by YahyaAlfayad** [Elias011/elias.js#9]
https://github.com/Elias011/elias.js/blob/abd1daee86c79d2e95b1644f7c387679bd2d6f06/week3/jhf.js#L88

This will work but it is better practice to have a shorter id. an example could be using `i + '_img'`. That way it is guaranteed to have the `id` unique and short. Same applicable for the rest of IDs

**Comment by Elias011** [comment]
Yes man you are right 
I fixed it
